# Generated by Django 4.2.1 on 2023-05-23 09:32

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auth',
            fields=[
                ('token', models.CharField(max_length=10240, primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=1024)),
                ('expired_at', core.models.UnixDateTImeField()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.CharField(primary_key=True, serialize=False, verbose_name=32)),
                ('uid', models.CharField(max_length=1024)),
                ('client_type', models.CharField(max_length=32)),
                ('client_version', models.IntegerField()),
                ('os', models.CharField(verbose_name=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.CharField(max_length=1024, primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=1024)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.CharField(max_length=1024, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
