# Generated by Django 4.2.2 on 2023-12-11 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='status',
            field=models.IntegerField(choices=[(1, 'Normal'), (-1, 'Soft Del'), (-2, 'Hard Del')], default=1),
        ),
    ]
