# Generated by Django 5.1.7 on 2025-03-12 03:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_note_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Auth',
        ),
        migrations.RemoveField(
            model_name='user',
            name='uid',
        ),
        migrations.AddField(
            model_name='user',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=1024, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='client_id',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='os',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='note',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=1024, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
