# Generated by Django 5.1.7 on 2025-09-28 03:12

from django.db import migrations, models


def copy_created_at_to_updated_at(apps, schema_editor):
    Client = apps.get_model('core', 'Client')
    Client.objects.update(updated_at=models.F("created_at"))


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_auth_remove_user_uid_user_id_user_last_login_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RunPython(copy_created_at_to_updated_at, reverse_code=migrations.RunPython.noop),
    ]
